# Generated by Django 3.2.11 on 2022-02-06 14:58

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('wa_id', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20)),
                ('blacklist', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('host', models.CharField(max_length=254)),
                ('database', models.CharField(max_length=254)),
                ('user', models.CharField(max_length=254)),
                ('password', app.models.EncryptedField()),
                ('port', models.CharField(max_length=10)),
                ('driver', models.CharField(default='postgres', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=254, unique=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('api_key', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('namespace', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MKUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=254)),
                ('cd_servico', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mk_users',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('value', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('header', models.CharField(max_length=250, null=True)),
                ('header_args', models.IntegerField(default=0, null=True)),
                ('header_type', models.CharField(max_length=20, null=True)),
                ('body', models.CharField(max_length=1024, null=True)),
                ('body_args', models.IntegerField(default=0, null=True)),
                ('footer', models.CharField(max_length=250, null=True)),
                ('buttons', models.CharField(max_length=250, null=True)),
                ('buttons_args', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('token', models.CharField(max_length=254)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mk_tokens',
                'ordering': ['-expire_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('hsm', models.CharField(blank=True, max_length=254, null=True)),
                ('once_time', models.BooleanField(default=False)),
                ('task', models.CharField(blank=True, max_length=254, null=True)),
                ('sql', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.database')),
            ],
        ),
    ]
