# Generated by Django 3.2.11 on 2022-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='hsm',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
