# Generated by Django 3.2.11 on 2022-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_query_hsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='function',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
