# Generated by Django 3.2.11 on 2022-02-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_query_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='function',
            new_name='task',
        ),
    ]
