# Generated by Django 3.2.11 on 2022-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mkuser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('header', models.CharField(max_length=250, null=True)),
                ('header_args', models.IntegerField(default=0)),
                ('header_type', models.CharField(max_length=20, null=True)),
                ('body', models.CharField(max_length=250, null=True)),
                ('body_args', models.IntegerField(default=0)),
                ('footer', models.CharField(max_length=250, null=True)),
                ('buttons', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'dialog_templates',
            },
        ),
    ]
