# Generated by Django 3.2.11 on 2022-02-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
