# Generated by Django 3.2.11 on 2022-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220205_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body_args',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='header_args',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
