# Generated by Django 3.2.11 on 2022-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220205_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='once_time',
            field=models.BooleanField(default=False),
        ),
    ]
