# Generated by Django 3.2.11 on 2022-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_query_once_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='buttons_args',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
