# Generated by Django 3.2.11 on 2022-02-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_dialog_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='namespace',
        ),
    ]
