# Generated by Django 3.2.11 on 2022-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_dialog_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='namespace',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
